export const richPresenceValues = {
  team: {
    '*': 'Unknown Team',
    0x1b321: 'Adelaide United',
    0x1b323: 'Brisbane Roar',
    0x1b324: 'Central Coast',
    0x1b325: 'Melb. Victory',
    0x1b660: 'Melbourne Heart',
    0x1b326: 'Newcastle Jets',
    0x1b327: 'Perth Glory',
    0x1b328: 'Sydney FC',
    0x1b72b: 'Wanderers',
    0x1b496: 'Well. Phoenix',
    0x1b4cd: 'Admira',
    0x100: 'FK Austria',
    0x7fd: 'Innsbruck',
    0xbf: 'RB Salzburg',
    0xfe: 'SK Rapid Wien',
    0xd1: 'SK Sturm Graz',
    0x1b596: 'SV Grödig',
    0x30c: 'SV Ried',
    0x1b30d: 'Wiener Neustadt',
    0x1b4ce: 'Wolfsberger AC',
    0x131: 'Bohemians FC',
    0x346: 'Bray Wanderers',
    0x1a6: 'Cork City',
    0x1bd: 'Derry City',
    0x624: 'Drogheda Utd',
    0x345: 'Dundalk',
    0x1b2b5: 'Limerick',
    0x132: 'Shamrock Rovers',
    0x342: 'Shelbourne',
    0x233: 'Sligo Rovers',
    0x1a7: 'St. Pats',
    0x1b21c: 'UCD AFC',
    0x1b703: 'Al-Ahli',
    0x1b5e0: 'Al-Ettifaq',
    0x1b705: 'Al-Faisaly',
    0x1b706: 'Al-Fateh',
    0x25d: 'Al-Hilal',
    0x25f: 'Al-Ittihad',
    0x1b824: 'Al-Nahdha',
    0x1b60b: 'Al-Nassr',
    0x1b823: 'Al-Orubah FC',
    0x1b708: 'Al-Raed',
    0x1b43a: 'Al-Shabab',
    0x1b709: 'Al-Taawoun',
    0x1b717: 'Alshoulla',
    0x1b70b: 'Najran',
    0x1b1: 'AIK Fotboll',
    0x1b4db: 'Åtvidabergs FF',
    0x2c7: 'BK Häcken',
    0x1b459: 'Brommapojkarna',
    0x2c6: 'Djurgårdens IF',
    0x1b2ad: 'Gefle IF',
    0x141: 'Halmstads BK',
    0x1b0: 'Helsingborgs IF',
    0x2bc: 'IF Elfsborg',
    0x13f: 'IFK Göteborg',
    0x2be: 'IFK Norrköping',
    0x59f: 'Kalmar FF',
    0x140: 'Malmö FF',
    0x1b5c8: 'Mjällby AIF',
    0x74e: 'Östers IF',
    0x1b68b: 'Syrianska',
    0x01: 'Arsenal',
    0x02: 'Aston Villa',
    0x7a9: 'Cardiff City',
    0x05: 'Chelsea',
    0x707: 'Crystal Palace',
    0x07: 'Everton',
    0x90: 'Fulham',
    0x7a0: 'Hull City',
    0x09: 'Liverpool',
    0x0a: 'Manchester City',
    0x0b: 'Manchester United',
    0x0d: 'Newcastle United',
    0x700: 'Norwich City',
    0x11: 'Southampton',
    0x12: 'Spurs',
    0x70e: 'Stoke City',
    0x6a: 'Sunderland',
    0x7a8: 'Swansea City',
    0x6d: 'West Brom',
    0x13: 'West Ham',
    0xab: '1. FC Nuremberg',
    0xa9: '1. FSV Mainz 05',
    0x272d: '1899 Hoffenheim',
    0x20: 'Bayer 04',
    0x16: 'Bor. Dortmund',
    0x17: "Bor. M'gladbach",
    0x1afa4: 'Braunschweig',
    0x720: 'Eint. Frankfurt',
    0x18839: 'FC Augsburg',
    0x15: 'FC Bayern Munich',
    0x22: 'FC Schalke 04',
    0x1c: 'Hamburger SV',
    0x1e5: 'Hannover 96',
    0xa6: 'Hertha BSC',
    0x19: 'SC Freiburg',
    0x24: 'VfB Stuttgart',
    0xaf: 'VfL Wolfsburg',
    0x26: 'Werder Bremen',
    0x1d: "1. FC K'lautern",
    0x1f: '1. FC Koln',
    0x21: '1860 Munich',
    0x9f: 'Arm. Bielefeld',
    0x1f7: 'Dynamo Dresden',
    0xa2: 'Energie Cottbus',
    0x1fa: 'Erzgebirge Aue',
    0x1b02c: 'F. Düsseldorf',
    0x1b287: 'FC Ingolstadt',
    0x1aef9: 'FC St. Pauli',
    0x1b004: 'FSV Frankfurt',
    0xa5: 'Greuther Fürth',
    0x728: 'Karlsruher SC',
    0x272e: 'SC Paderborn',
    0x1ae62: 'SV Sandhausen',
    0x727: 'Union Berlin',
    0xa0: 'VfL Bochum',
    0x226: 'VfR Aalen',
    0x18ae9: 'Audax Italiano',
    0x1b795: 'CD Antofagasta',
    0x1b183: 'CD Cobreloa',
    0x1b182: 'CD Cobresal',
    0x1b7c8: 'CD Everton',
    0x1b2df: 'CD Huachipato',
    0x1b5f4: "CD O'Higgins",
    0x1b2e0: 'CD Palestino',
    0x1b184: 'Colo-Colo',
    0x1b793: 'Depor. Iquique',
    0x1b7c9: 'Ñublense',
    0x1b5ee: 'Rangers Talca',
    0x1b17f: 'Uni. Católica',
    0x1b796: 'Uni. Concepción',
    0x3ab5: 'Uni. de Chile',
    0x1b181: 'Unión Española',
    0x1b797: 'Unión La Calera',
    0x1b180: 'Wanderers',
    0x1b09b: 'Cracovia Kraków',
    0x1a4: 'Górnik Zabrze',
    0x1b099: 'Jag. Białystok',
    0x1b1eb: 'Korona Kielce',
    0x369: 'Lech Poznań',
    0x1b1f3: 'Lechia Gdańsk',
    0x74f: 'Legia Warszawa',
    0x1b1ee: 'Piast Gliwice',
    0x1b1ef: 'Podbeskidzie',
    0x1b09a: 'Pogoń Szczecin',
    0x36a: 'Ruch Chorzów',
    0x1b1f4: 'Śląsk Wrocław',
    0x12d: 'Widzew Łódź',
    0x751: 'Wisła Kraków',
    0x1b09d: 'Zagłębie Lubin',
    0x1b780: 'Zaw. Bydgoszcz',
    0x28a: 'ADO Den Haag',
    0xf5: 'Ajax',
    0x772: 'AZ',
    0x77b: 'FC Groningen',
    0x774: 'FC Twente',
    0x76f: 'FC Utrecht',
    0xf6: 'Feyenoord',
    0x18918: 'Go Ahead Eagles',
    0x1891a: 'Heracles Almelo',
    0x776: 'N.E.C.',
    0x770: 'NAC Breda',
    0x77a: 'PEC Zwolle',
    0xf7: 'PSV',
    0x771: 'RKC Waalwijk',
    0x76e: 'Roda JC',
    0x287: 'SC Cambuur',
    0x779: 'sc Heerenveen',
    0x775: 'Vitesse',
    0x78c: 'Barnsley',
    0x58: 'Birmingham City',
    0x03: 'Blackburn Rvrs',
    0x786: 'Blackpool',
    0x04: 'Bolton',
    0x797: 'Bournemouth',
    0x710: 'Brighton',
    0x704: 'Burnley',
    0x59: 'Charlton Ath',
    0x5b: 'Derby County',
    0x8e: 'Doncaster',
    0x793: 'Huddersfield',
    0x5e: 'Ipswich Town',
    0x08: 'Leeds United',
    0x5f: 'Leicester City',
    0x0c: 'Middlesbrough',
    0x61: 'Millwall',
    0x0e: "Nott'm Forest",
    0x0f: 'QPR',
    0x701: 'Reading',
    0x70f: 'Sheffield Wed',
    0x703: 'Watford',
    0x77d: 'Wigan Athletic',
    0x15a: 'Yeovil Town',
    0x70c: 'Bradford City',
    0x785: 'Brentford',
    0x77f: 'Bristol City',
    0x5c8: 'Carlisle United',
    0x78f: 'Colchester',
    0x708: 'Coventry City',
    0x1b12a: 'Crawley Town',
    0x79: 'Crewe Alexandra',
    0x70a: 'Gillingham',
    0x7a6: 'Leyton Orient',
    0x706: 'MK Dons',
    0x791: 'Notts County',
    0x780: 'Oldham Athletic',
    0x792: 'Peterborough',
    0x788: 'Port Vale',
    0x709: 'Preston',
    0x705: 'Rotherham Utd',
    0x702: 'Sheffield Utd',
    0x7f: 'Shrewsbury',
    0x169: 'Stevenage',
    0x78e: 'Swindon Town',
    0x3ac8: 'Tranmere Rovers',
    0x70b: 'Walsall',
    0x6e: 'Wolverhampton',
    0x1aee9: 'Accrington',
    0x1b683: 'AFC Wimbledon',
    0x7aa: 'Bristol Rovers',
    0x3aa7: 'Burton Albion',
    0x799: 'Bury',
    0x790: 'Cheltenham Town',
    0x784: 'Chesterfield',
    0x175: 'Dagenham',
    0x8f: 'Exeter City',
    0x1b684: 'Fleetwood Town',
    0x795: 'Hartlepool',
    0x794: 'Mansfield Town',
    0x165: 'Morecambe',
    0x1b67e: 'Newport County',
    0x78a: 'Northampton',
    0x79f: 'Oxford United',
    0x789: 'Plymouth Argyle',
    0x6fe: 'Portsmouth',
    0x7a3: 'Rochdale',
    0x79d: 'Scunthorpe Utd',
    0x7a2: 'Southend United',
    0x79a: 'Torquay United',
    0x78d: 'Wycombe',
    0x79c: 'York City',
    0x559: 'Argentina',
    0x587: 'Australia',
    0x52a: 'Austria',
    0x52d: 'Belgium',
    0x1b35b: 'Bolivia',
    0x55a: 'Brazil',
    0x52f: 'Bulgaria',
    0x573: 'Cameroon',
    0x1b363: 'Chile',
    0x1b205: 'Colombia',
    0x1b208: "Côte d'Ivoire",
    0x532: 'Czech Republic',
    0x533: 'Denmark',
    0x1b369: 'Ecuador',
    0x1b21a: 'Egypt',
    0x526: 'England',
    0x536: 'Finland',
    0x537: 'France',
    0x539: 'Germany',
    0x53a: 'Greece',
    0x75e: 'Hungary',
    0x1b36a: 'India',
    0x54b: 'Ireland',
    0x53f: 'Italy',
    0x3ce: 'Korea Republic',
    0x56a: 'Mexico',
    0x1b420: 'Netherlands',
    0x1b371: 'New Zealand',
    0x1ae01: 'Northern Ireland',
    0x548: 'Norway',
    0x1b204: 'Peru',
    0x549: 'Poland',
    0x54a: 'Portugal',
    0x54c: 'Romania',
    0x54d: 'Russia',
    0x54f: 'Scotland',
    0x551: 'Slovenia',
    0x1b1fb: 'South Africa',
    0x552: 'Spain',
    0x553: 'Sweden',
    0x554: 'Switzerland',
    0x555: 'Turkey',
    0x56b: 'United States',
    0x561: 'Uruguay',
    0x557: 'Wales',
    0x5c4: "Busan I'Park",
    0x5c3: 'Chunnam Dragons',
    0x808: 'Daegu FC',
    0x3d4: 'Daejon Citizen',
    0x3d6: 'FC Seoul',
    0x1b5f3: 'Gangwon FC',
    0x1b3e4: 'GyeongNam FC',
    0x1b0ad: 'Incheon United',
    0x5c6: 'Jeju United FC',
    0x5c5: 'Jeonbuk FC',
    0x5c2: 'Pohang Steelers',
    0x3d5: 'Seongnam Ilhwa',
    0x3d7: 'Suwon Bluewings',
    0x5c1: 'Ulsan Hyundai',
    0x189df: 'AD Alcorcón',
    0x1b0ef: 'CD Lugo',
    0x1adf5: 'CD Mirandés',
    0x1dd: 'CD Numancia',
    0x104: 'CD Tenerife',
    0x74b: 'Córdoba CF',
    0x1cf: 'Deport. Alavés',
    0x1b070: 'FC Barcelona B',
    0x1adee: 'Girona CF',
    0x18a0f: 'Hércules CF',
    0xf2: 'RC Deportivo',
    0x23b: 'RC Recreativo',
    0x1c5: 'RCD Mallorca',
    0x1d7: 'Real Jaén CF',
    0x73f: 'Real Murcia CF',
    0xf4: 'Real Zaragoza',
    0x1b076: 'RM Castilla',
    0x3aad: 'Sabadell FC',
    0x1d3: 'SD Eibar',
    0x7e7: 'SD Ponferradina',
    0x1cb: 'Sporting Gijón',
    0x1d8: 'UD Las Palmas',
    0x757: 'América',
    0x18afc: 'Atlante',
    0x18afa: 'Atlas',
    0x1ae47: 'Chiapas',
    0x1b0bd: 'Club León',
    0x756: 'Cruz Azul',
    0x758: 'Guadalajara',
    0x404: 'Monarcas',
    0x408: 'Monterrey',
    0x1ae43: 'Pachuca',
    0x1ae48: 'Puebla',
    0x1ae46: 'Querétaro',
    0x1ae40: 'Santos Laguna',
    0x7b2: 'Tigres',
    0x1b43e: 'Tijuana',
    0x75a: 'Toluca',
    0x759: 'U.N.A.M.',
    0x1ae41: 'Veracruz',
    0x1c0: 'Athletic Bilbao',
    0xf0: 'Atlético Madrid',
    0x1df: 'CA Osasuna',
    0x1c2: 'Celta Vigo',
    0x1d4: 'Elche CF',
    0xf1: 'FC Barcelona',
    0x744: 'Getafe CF',
    0x1b0f0: 'Granada CF',
    0x73d: 'Levante UD',
    0x23d: 'Málaga CF',
    0x1e0: 'Rayo Vallecano',
    0x1c4: 'RCD Espanyol',
    0x1c1: 'Real Betis',
    0xf3: 'Real Madrid',
    0x1c9: 'Real Sociedad',
    0x1ce: 'Real Valladolid',
    0x1e1: 'Sevilla FC',
    0x745: 'UD Almería',
    0x1cd: 'Valencia CF',
    0x1e3: 'Villarreal CF',
    0x40b: 'Atl. Mineiro',
    0x40f: 'Atl. Paranaense',
    0x63e: 'Bahia',
    0x205: 'Botafogo',
    0x411: 'Corinthians',
    0x1b1c4: 'Coritiba',
    0x1b1c6: 'Criciúma',
    0x238: 'Cruzeiro',
    0x413: 'Flamengo',
    0x237: 'Fluminense',
    0x1b1c2: 'Goiás',
    0x65d: 'Grêmio',
    0x418: 'Internacional',
    0x1b1ca: 'Náutico',
    0x1b1c3: 'Ponte Preta',
    0x1b2bc: 'Portuguesa',
    0x41d: 'Santos',
    0x256: 'São Paulo',
    0x239: 'Vasco da Gama',
    0x6b7: 'Vitória',
    0x76d: 'Académica',
    0x1b781: 'Arouca',
    0x761: 'Belém',
    0x765: 'C. Funchal',
    0x763: 'CD Nacional',
    0x2724: 'Estoril',
    0xec: 'FC Porto',
    0x764: 'Paços Ferreira',
    0x2e8: 'Rio Ave FC',
    0x1b3b4: 'S.C. Olhanense',
    0x768: 'SC Braga',
    0xea: 'SL Benfica',
    0xed: 'Sporting CP',
    0x760: 'V. Barcelos',
    0x75f: 'Vit. Guimarães',
    0x299: 'Vitória FC',
    0x1b7c3: 'Al. Petrolera',
    0x18aec: 'Atl. Nacional',
    0x1b790: 'Atlético Huila',
    0x1b593: 'Boyacá Chicó',
    0x1b469: 'Cúcuta Depor.',
    0x1b78d: 'Deport. Quindío',
    0x1b46a: 'Deportes Tolima',
    0x18aee: 'Deportivo Cali',
    0x1b46b: 'Deportivo Pasto',
    0x1b78e: 'Envigado',
    0x18af0: 'Ind. Santa Fe',
    0x18aef: 'Indep. Medellín',
    0x1b7c2: 'Itagüí',
    0x18aed: 'Junior FC',
    0x1b78b: 'La Equidad',
    0x18af1: 'Millonarios FC',
    0x18af2: 'Once Caldas',
    0x1b78f: 'Patriotas FC',
    0x266: 'AC Ajaccio',
    0x45: 'AS Monaco',
    0x3b: 'Bordeaux',
    0x3e: 'EA Guingamp',
    0x1b2a7: 'Evian Thonon FC',
    0xd9: 'FC Lorient',
    0x47: 'FC Nantes',
    0xe2: 'FC Sochaux',
    0x41: 'LOSC Lille',
    0xdb: 'Marseille',
    0x46: 'Montpellier HSC',
    0x48: 'OGC Nice',
    0x42: 'Olumpique Lyon',
    0x49: 'PSG',
    0x71b: 'Saint-Etienne',
    0x3a: 'SC Bastia',
    0x17b: 'Stade Reims',
    0x4a: 'Stade Rennais',
    0x711: 'Toulouse FC',
    0x1af78: 'Valenciennes FC',
    0x1b575: 'AC Arles',
    0x39: 'AJ Auxerre',
    0x5fa: 'Angers SCO',
    0x71f: 'AS Nancy',
    0x1b7a5: 'CA Bastia',
    0x715: 'Cham. Niortais',
    0x717: 'Clermont Foot',
    0x1afe9: 'Dijon FCO',
    0x126: 'ES Troyes',
    0x71c: 'FC Istres',
    0x44: 'FC Metz',
    0xd4: 'LB Chateauroux',
    0x6ca: 'Le Havre AC',
    0xe0: 'Nîmes Olympique',
    0x40: 'RC Lens',
    0xd2: 'SM Caen',
    0x17a: 'Stade Brest',
    0x716: 'Stade Lavallois',
    0x1aef6: 'Tours FC',
    0x714: 'US Créteil',
    0x2b5: 'Chicago Fire',
    0x1b1de: 'Chivas USA',
    0x2b6: 'Colorado Rapids',
    0x2af: 'Columbus Crew',
    0x2b0: 'D.C. United',
    0x2b7: 'FC Dallas',
    0x2ba: 'Houston Dynamo',
    0x2b9: 'LA Galaxy',
    0x1b223: 'Montreal Impact',
    0x2b3: 'New England',
    0x2b1: 'NY Red Bulls',
    0x1b606: 'Philadelphia',
    0x1b224: 'Portland',
    0x1b1d9: 'Real Salt Lake',
    0x1b538: 'SJ Earthquakes',
    0x1b228: 'Sounders FC',
    0x2b8: 'Sporting KC',
    0x1b423: 'Toronto FC',
    0x18af8: 'Whitecaps FC',
    0x1b465: 'All Boys',
    0x1b1ab: 'Argentinos Jrs.',
    0x1af3a: 'Arsenal',
    0x1af38: 'Atlético Rafaela',
    0x1b1ae: 'Belgrano',
    0x755: 'Boca Juniors',
    0x1af46: 'Colón',
    0x18adb: 'Estudiantes',
    0x18adc: 'Gimnasia',
    0x1b45a: 'Godoy Cruz',
    0x1af3b: 'Lanús',
    0x1af3c: "Newell's",
    0x1af3e: 'Olimpo',
    0x1afda: 'Quilmes',
    0x18add: 'Racing Club',
    0x754: 'River Plate',
    0x1aff4: 'Rosario Ctral.',
    0x3f5: 'San Lorenzo',
    0x1b463: 'Tigre',
    0x18ae0: 'Vélez Sarsfield',
    0x6d6: 'Cercle Brugge',
    0xe7: 'Club Brugge',
    0x2a2: 'KAA Gent',
    0x2a1: 'KRC Genk',
    0x186f1: 'KV Kortrijk',
    0x1b084: 'KV Mechelen',
    0x2aa: 'KV Oostende',
    0xef: 'Lierse SK',
    0x186f7: 'OHL',
    0x6d3: 'RAEC Mons',
    0xe5: 'RSC Anderlecht',
    0x29e: 'Sp. Charleroi',
    0x7d7: 'Sport. Lokeren',
    0xe8: 'Standard Liège',
    0x1b141: 'Waasl.-Beveren',
    0x3a9d: 'Zulte-Waregem',
    0x384: 'BSC Young Boys',
    0x1b2: 'FC Aarau',
    0x380: 'FC Basel',
    0x746: 'FC Lausanne',
    0x381: 'FC Luzern',
    0x1b0b2: 'FC Sion',
    0x382: 'FC St. Gallen',
    0x6b3: 'FC Thun',
    0x37e: 'FC Zürich',
    0x142: 'Grasshopper',
    0x116: 'AEK Athens',
    0x18ac3: 'FC Shakhtar',
    0x145: 'Galatasaray SK',
    0x1ae0d: 'Independiente',
    0x1b151: 'Kaizer Chiefs',
    0x118: 'Olympiakos CFP',
    0x1b152: 'Orlando Pirates',
    0x17f: 'Palmeiras',
    0x75c: 'Panathinaikos',
    0x189: 'PAOK',
    0x56: 'Rangers',
    0x1899e: 'A. Makhachkala',
    0x1ae9a: 'Amkar Perm',
    0x13b: 'CSKA Moskva',
    0x138: 'Dynamo Moskva',
    0x1b65a: 'FC Krasnodar',
    0x1ae97: 'FC Rostov',
    0x1ae99: 'FC Tom Tomsk',
    0x1b2a0: 'FC Ural',
    0x1899c: 'Krylya Sovetov',
    0x1ae09: 'Kuban Krasnodar',
    0x1899d: 'Lokomotiv',
    0x1ae93: 'Rubin Kazan',
    0x1899f: 'Spartak Moskva',
    0x1ae1d: 'Terek Grozny',
    0x1b659: 'Volga',
    0x189a1: 'Zenit',
    0x4d: 'Aberdeen',
    0x4e: 'Celtic',
    0xb5: 'Dundee United',
    0x50: 'Hearts',
    0x51: 'Hibernian',
    0x26c: 'Inverness CT',
    0x52: 'Kilmarnock',
    0x53: 'Motherwell',
    0x6da: 'Patrick Thistle',
    0x277: 'Ross County',
    0x189c4: 'St. Johnstone',
    0x189c5: 'St. Mirren',
    0x27: 'Atalanta',
    0xbd: 'Bologna',
    0x732: 'Cagliari',
    0x1af1c: 'Catania',
    0xc0: 'Chievo Verona',
    0x1af26: 'Fiorentina',
    0x1afdc: 'Genoa',
    0xce: 'Hellas Verona',
    0x2c: 'Inter',
    0x2d: 'Juventus',
    0x2e: 'Lazio',
    0x734: 'Livorno',
    0x2f: 'Milan',
    0x30: 'Napoli',
    0x32: 'Parma',
    0x34: 'Roma',
    0x72d: 'Sampdoria',
    0x1b566: 'Sassuolo',
    0x36: 'Torino',
    0x37: 'Udinese',
    0x7f6: 'Avellino',
    0x738: 'Bari',
    0xbe: 'Brescia',
    0x1b5fc: 'C. Stabia',
    0x1b719: 'Carpi',
    0x1b143: 'Cesena',
    0x1b579: 'Cittadella',
    0x1b08e: 'Crotone',
    0x6d2: 'Empoli',
    0x1b095: 'La Spezia',
    0x1b594: 'Lanciano',
    0x1b767: 'Latina',
    0x6d0: 'Modena',
    0x1b661: 'Novara',
    0x1b140: 'Padua',
    0x733: 'Palermo',
    0xc8: 'Pescara',
    0xcb: 'Reggio Calabria',
    0x72e: 'Siena',
    0x23a: 'Terni',
    0x1b71a: 'Trapani',
    0x1b66d: 'Varese',
    0x334: 'Aalborg BK',
    0x10f: 'Aarhus GF',
    0x10d: 'Brøndby IF',
    0x5a5: 'Esbjerg fB',
    0x333: 'FC København',
    0x5ec: 'FC Midtjylland',
    0x6fc: 'FC Nordsjælland',
    0x1b728: 'FC Vestsjælland',
    0x110: 'Odense Boldklub',
    0x6fa: 'Randers FC',
    0x5a7: 'SønderjyskE',
    0x5a3: 'Viborg FF',
    0x6db: 'Aalesunds FK',
    0x5b7: 'FK Haugesund',
    0x731: 'Hønefoss BK',
    0x12b: 'Lillestrøm SK',
    0x1a1: 'Molde FK',
    0x5b0: 'ODD',
    0x12a: 'Rosenborg BK',
    0x1b6f6: 'Sandnes Ulf',
    0x1b647: 'Sarpsborg',
    0x397: 'SK Brann',
    0x5b9: 'Sogndal',
    0x5f4: 'Start',
    0x39a: 'Strømsgodset IF',
    0x1a2: 'Tromsø IL',
    0x398: 'Vålerenga',
    0x12c: 'Viking FK',
    0x1b265: 'Classic XI',
    0x1b1e0: 'World XI',
  },
  stadium: {
    '*': 'Unknown Stadium',
    0x01: 'Old Trafford',
    0x04: 'Stade Gerland',
    0x05: 'San Siro',
    0x06: 'Camp Nou',
    0x09: 'Signal Iduna Park',
    0x0a: 'Estadio Mestalla',
    0x0d: 'Anfield',
    0x0e: 'Parc des Princes',
    0x0f: 'Amsterdam ArenA',
    0x10: 'Stade Felix Bollaert',
    0x11: 'Constant Vanden Stock',
    0x18: 'Olympic Style',
    0x19: 'Closed Square Style',
    0x1a: 'Forest Park Stadium',
    0x1b: 'Oval Style',
    0x1c: 'Stamford Bridge',
    0x1d: 'Stade Vélodrome',
    0x1e: 'Veltins Arena',
    0x20: 'Crown Lane',
    0x21: 'Union Park Stadium',
    0x22: 'Town Park',
    0x23: 'Euro Park',
    0x24: 'Div3 UK Style',
    0x25: 'Div 3 Euro Style',
    0x27: 'Rural Training',
    0x29: 'Imtech Arena',
    0x2a: 'Estadio Vicente Calderón',
    0x64: "St. James' Park",
    0x66: 'José Alvalade',
    0x68: 'Estadio Azteca',
    0x69: 'Generic Modern',
    0x6b: 'Estádio da Luz',
    0x6c: 'Seoul Sang-am Stadium',
    0x6e: 'Daegu Stadium',
    0x6f: 'Estádio do Dragão',
    0x74: 'White Hart Lane',
    0x75: 'Modern South American',
    0x76: 'Modern Euro',
    0x85: 'Mercedes-Benz Arena',
    0x86: 'HDI Arena',
    0x87: 'Olympiastadion',
    0x89: 'Allianz Arena',
    0x8a: 'Commerzbank Arena',
    0x9b: 'Wembley Stadium',
    0x9c: 'Emirates Stadium',
    0x9d: 'Stadio Olimpico',
    0xa3: 'Jalisco',
  },
  language: {
    0x747564: '🇳🇱',
    0x676e65: '🇬🇧',
    0x657266: '🇫🇷',
    0x726567: '🇩🇪',
    0x617469: '🇮🇹',
    0x78656d: '🇲🇽',
    0x6c6f70: '🇵🇱',
    0x726f70: '🇵🇹',
    0x617073: '🇪🇸',
  },
  mode: {
    0x00: 'Main Menu',
    0x01: 'Lounge',
    0x02: 'Career - Manager',
    0x03: 'Tournament',
    0x04: 'Career - Player',
    0x07: 'Kick-Off - Team',
    0x08: 'Kick-Off - Be a Pro',
    0x09: 'The Season',
    0x0a: 'Kick-Off - Be a Keeper',
    0x0b: 'Career - Coach',
  },
};

export const progressionAchievements = [
  {
    title: 'A Star in the Making',
    description: 'Finish your first season in Player Career.',
    modeId: 0x04,
  },
  {
    title: 'Taking on the Responsibility',
    description: 'Finish your first season in Player Coach Career.',
    modeId: 0x0b,
  },
  {
    title: 'Total Football Control',
    description: 'Finish your first season in Manager Career.',
    modeId: 0x02,
  },
];

export const careerAccomplishments = [
  {
    title: 'Hat Trick Hero',
    description: 'Score a hat trick with your pro in Career Mode.',
    points: 3,
    offset: 0x23f0,
  },
  {
    title: 'Elite Performance',
    description: 'Achieve a 10.0 match rating in Career Mode.',
    points: 3,
    offset: 0x244c,
  },
  {
    title: 'International Debut',
    description: 'Make the national team starting 11 in Player Career.',
    points: 3,
    offset: 0x24a8,
  },
  {
    title: 'Established Position',
    description: 'Win 5 national team matches in Player Career.',
    points: 4,
    offset: 0x2504,
  },
  {
    title: 'National Scorer',
    description: 'Score 10 goals for your country in Player Career.',
    points: 5,
    offset: 0x2560,
  },
  {
    title: 'National Hero',
    description: 'Captain your country in Player Career.',
    points: 5,
    offset: 0x25bc,
  },
  {
    title: 'National Legend',
    description: 'Reach "Legend" national level status in Player Career.',
    points: 10,
    offset: 0x2618,
  },
  {
    title: 'Killer Instinct',
    description: 'Finish a season as League Top Scorer in Player Career.',
    points: 5,
    offset: 0x2674,
  },
  {
    title: 'Treble',
    description: 'Finish a season with 3 trophies in Career Mode.',
    points: 5,
    offset: 0x26d0,
  },
  {
    title: 'Quadruple',
    description: 'Finish a season with 4 trophies in Career Mode.',
    points: 10,
    offset: 0x272c,
  },
  {
    title: 'The Other Side',
    description: 'Play a season as a defender in Player Career.',
    points: 3,
    offset: 0x2788,
  },
  {
    title: 'Maxed Out',
    description:
      'Upgrade a training skill to its maximum potential in Player Coach Career.',
    points: 3,
    offset: 0x27e4,
  },
  {
    title: 'Certified Legend',
    description: 'Achieve Legendary Fame in any Career Mode.',
    points: 25,
    offset: 0x2840,
  },
  {
    title: 'European Winners',
    description: 'Win the Euro League tournament in Manager Career.',
    points: 5,
    offset: 0x289c,
  },
  {
    title: 'European Champions',
    description: 'Win the Champions Cup tournament in Manager Career.',
    points: 5,
    offset: 0x28f8,
  },
  {
    title: 'Invincible',
    description: 'Achieve an undefeated season in Manager Career.',
    points: 10,
    offset: 0x2954,
  },
];

export const difficulties = {
  easy: 0x00,
  amateur: 0x01,
  semiPro: 0x02,
  professional: 0x03,
  worldClass: 0x04,
  legendary: 0x05,
};

export const UKAccomplishments = [
  {
    title: 'Hat Trick: United Kingdom',
    description:
      'Score a Hat Trick against any club from the United Kingdom in Professional difficulty or above.',
    points: 3,
    offset: 0x5c,
  },
  {
    title: 'Underdog: United Kingdom',
    description:
      'Defeat a 4+ star club from the United Kingdom with any 2 star club in Semi-Pro difficulty or above.',
    points: 3,
    offset: 0xb8,
  },
  {
    title: 'Barclays Premier League',
    description: 'Win the Barclays Premier League.',
    points: 5,
    offset: 0x114,
  },
  {
    title: 'Football League Championship',
    description: 'Win the Football League Championship.',
    points: 3,
    offset: 0x170,
  },
  {
    title: 'Football League 1',
    description: 'Win the Football League 1.',
    points: 3,
    offset: 0x1cc,
  },
  {
    title: 'Football League 2',
    description: 'Win the Football League 2.',
    points: 3,
    offset: 0x228,
  },
  {
    title: 'FA Cup',
    description: 'Win the FA Cup.',
    points: 3,
    offset: 0x284,
  },
  {
    title: 'Capital One Cup',
    description: 'Win the Capital One Cup.',
    points: 2,
    offset: 0x2e0,
  },
  {
    title: "Johnstone's Paint Trophy",
    description: "Win the Johnstone's Paint Trophy.",
    points: 2,
    offset: 0x33c,
  },
  {
    title: 'Scottish Premiership',
    description: 'Win the Scottish Premiership.',
    points: 3,
    offset: 0x398,
  },
  {
    title: 'Scottish Cup',
    description: 'Win the Scottish Cup.',
    points: 2,
    offset: 0x3f4,
  },
];

export const westernEuropeAccomplishments = [
  {
    title: 'Possession: Western Europe',
    description:
      'Achieve 75%+ Possession in Professional difficulty or above against a club from Western Europe.',
    points: 3,
    offset: 0x450,
  },
  {
    title: 'Late Goal: Western Europe',
    description:
      'Score with a player subbed in after 85+ minutes against a club from Western Europe in Semi-Pro difficulty or above.',
    points: 3,
    offset: 0x4ac,
  },
  {
    title: '5 Minutes: Western Europe',
    description:
      'Score in under 5 minutes against a club from Western Europe in Semi-Pro difficulty or above.',
    points: 3,
    offset: 0x508,
  },
  {
    title: 'Ligue 1',
    description: 'Win the Ligue 1.',
    points: 5,
    offset: 0x5c0,
  },
  {
    title: 'Ligue 2',
    description: 'Win the Ligue 2.',
    points: 3,
    offset: 0x61c,
  },
  {
    title: 'Coupe Nationale',
    description: 'Win the Coupe Nationale.',
    points: 3,
    offset: 0x678,
  },
  {
    title: 'Coupe de la Ligue',
    description: 'Win the Coupe de la Ligue.',
    points: 2,
    offset: 0x6d4,
  },
  {
    title: 'Eredivisie',
    description: 'Win the Eredivisie.',
    points: 3,
    offset: 0x730,
  },
  {
    title: 'Dutch Cup',
    description: 'Win the Dutch Cup.',
    points: 2,
    offset: 0x78c,
  },
  {
    title: 'Belgium Pro League',
    description: 'Win the Belgium Pro League.',
    points: 3,
    offset: 0x7e8,
  },
  {
    title: 'Coupe de Belgique',
    description: 'Win the Coupe de Belgique.',
    points: 2,
    offset: 0x844,
  },
];

export const ligue1Clubs = [
  0x266, 0x45, 0x3b, 0x3e, 0x1b2a7, 0xd9, 0x47, 0xe2, 0x41, 0xdb, 0x46, 0x48,
  0x42, 0x71b, 0x3a, 0x17b, 0x4a, 0x711, 0x1af78,
];

export const eredivisieClubs = [
  0x28a, 0x772, 0x77b, 0x774, 0x76f, 0xf6, 0x18918, 0x1891a, 0x776, 0x770,
  0x77a, 0xf7, 0x771, 0x76e, 0x287, 0x779, 0x775,
];

export const southernEuropeAccomplishments = [
  {
    title: 'Shoot-Out: Southern Europe',
    description:
      'Win a penalty kick shootout in Semi-Pro difficulty or above against a club from Southern Europe.',
    points: 2,
    offset: 0x8a0,
  },
  {
    title: 'Possession: Southern Europe',
    description:
      'Achieve over 75% Possession in Amateur difficulty or above against a club from Southern Europe.',
    points: 2,
    offset: 0x8fc,
  },
  {
    title: '5 Goals: Southern Europe',
    description:
      'Win by 5 goals or more in Amateur difficulty or above against a club from Southern Europe.',
    points: 3,
    offset: 0x958,
  },
  {
    title: 'Liga BBVA',
    description: 'Win the Liga BBVA.',
    points: 5,
    offset: 0xa10,
  },
  {
    title: 'Liga Adelante',
    description: 'Win the Liga Adelante.',
    points: 3,
    offset: 0xa6c,
  },
  {
    title: 'Spanish Cup',
    description: 'Win the Spanish Cup.',
    points: 3,
    offset: 0xac8,
  },
  {
    title: 'Serie A',
    description: 'Win the Serie A Italia.',
    points: 5,
    offset: 0xb24,
  },
  {
    title: 'Serie B',
    description: 'Win the Serie B Italia.',
    points: 3,
    offset: 0xb80,
  },
  {
    title: 'Coppa Nazionale',
    description: 'Win the Coppa Nazionale.',
    points: 3,
    offset: 0xbdc,
  },
  {
    title: 'Liga Portugal',
    description: 'Win the Liga Portuguesa.',
    points: 5,
    offset: 0xc38,
  },
  {
    title: 'Taça de Portugal',
    description: 'Win the Taça de Portugal.',
    points: 3,
    offset: 0xc94,
  },
];

export const serieAClubs = [
  0x27, 0xbd, 0x732, 0x1af1c, 0xc0, 0x1af26, 0x1afdc, 0xce, 0x2c, 0x2e, 0x734,
  0x2f, 0x30, 0x32, 0x34, 0x72d, 0x1b566, 0x36, 0x37,
];

export const centralEuropeAccomplishments = [
  {
    title: 'Shoot-Out: Central Europe',
    description:
      'Win a penalty kick shootout in World Class difficulty or above against a club from Central Europe.',
    points: 3,
    offset: 0xcf0,
  },
  {
    title: '5 Minutes: Central Europe',
    description:
      'Score in under 5 minutes against a club from Central Europe in Professional difficulty or above',
    points: 4,
    offset: 0xd4c,
  },
  {
    title: 'Bundesliga',
    description: 'Win the German Bundesliga.',
    points: 5,
    offset: 0xe60,
  },
  {
    title: '2. Bundesliga',
    description: 'Win the German 2. Bundesliga.',
    points: 3,
    offset: 0xebc,
  },
  {
    title: 'DFB Pokal',
    description: 'Win the Deutscher Pokal.',
    points: 3,
    offset: 0xf18,
  },
  {
    title: 'Raiffeisen Super League',
    description: 'Win the Raiffeisen Super League.',
    points: 3,
    offset: 0xf74,
  },
  {
    title: 'Swiss Cup',
    description: 'Win the Swiss Cup.',
    points: 2,
    offset: 0xfd0,
  },
  {
    title: 'Austrian Bundesliga',
    description: 'Win the Austrian Bundesliga.',
    points: 3,
    offset: 0x102c,
  },
  {
    title: 'ÖFB-Samsung-Cup',
    description: 'Win the ÖFB-Samsung-Cup.',
    points: 2,
    offset: 0x1088,
  },
];

export const bundesligaClubs = [
  0xab, 0xa9, 0x272d, 0x20, 0x16, 0x17, 0x1afa4, 0x720, 0x18839, 0x22, 0x1c,
  0x1e5, 0xa6, 0x19, 0x24, 0xaf, 0x26,
];

export const americasAccomplishments = [
  {
    title: 'Stay Ahead: The Americas',
    description:
      'Score and maintain a 2 goal lead in Semi-Pro difficulty or above against a club from the Americas.',
    points: 3,
    offset: 0x10e4,
  },
  {
    title: 'Passing: The Americas',
    description:
      'Achieve 75%+ Passing in Professional difficulty or above against a club from the Americas and win.',
    points: 3,
    offset: 0x1140,
  },
  {
    title: 'MLS Cup',
    description: 'Win the MLS Cup.',
    points: 3,
    offset: 0x1254,
  },
  {
    title: 'US Open Cup',
    description: 'Win the US Open Cup.',
    points: 2,
    offset: 0x12b0,
  },
  {
    title: 'Clausura',
    description: 'Win the LIGA Bancomer MX: Clausura.',
    points: 3,
    offset: 0x130c,
  },
  {
    title: 'Apertura',
    description: 'Win the LIGA Bancomer MX: Apertura.',
    points: 3,
    offset: 0x1368,
  },
  {
    title: 'Liga do Brasil',
    description: 'Win the Liga do Brasil.',
    points: 5,
    offset: 0x13c4,
  },
  {
    title: 'Copa do Brasil',
    description: 'Win the Copa do Brasil.',
    points: 3,
    offset: 0x1420,
  },
  {
    title: 'Americas Club Championship',
    description: 'Win the Americas Club Championship.',
    points: 5,
    offset: 0x147c,
  },
];

export const scandinaviaAccomplishments = [
  {
    title: 'Scandinavian Accuracy',
    description:
      'Achieve 90% Shots on Target in Semi-Pro difficulty or above against a Scandinavian club.',
    points: 2,
    offset: 0x14d8,
  },
  {
    title: 'Clean Sheet: Scandinavia',
    description:
      'Win a match with a clean sheet against a club from Scandinavia in Semi-Pro difficulty.',
    points: 2,
    offset: 0x1534,
  },
  {
    title: 'Fair Play: Scandinavia',
    description:
      'Win a match without bookings in Professional difficulty or above against a Scandinavian club.',
    points: 3,
    offset: 0x1590,
  },
  {
    title: 'Passing: Scandinavia',
    description:
      'Achieve 85%+ in Passing in Amateur difficulty or above against a Scandinavian club.',
    points: 2,
    offset: 0x15ec,
  },
  {
    title: 'Allsvenskan',
    description: 'Win the Allsvenskan.',
    points: 3,
    offset: 0x1700,
  },
  {
    title: 'Swedish Cup',
    description: 'Win the Swedish Cup.',
    points: 2,
    offset: 0x175c,
  },
  {
    title: 'Tippeligaen',
    description: 'Win the Tippeligaen.',
    points: 3,
    offset: 0x17b8,
  },
  {
    title: 'NM SAS Braathens Cup',
    description: 'Win the NM SAS Braathens Cup.',
    points: 2,
    offset: 0x1814,
  },
  {
    title: 'Superliga',
    description: 'Win the Superliga.',
    points: 3,
    offset: 0x1870,
  },
  {
    title: 'DBU Pokalen',
    description: 'Win the DBU Pokalen.',
    points: 2,
    offset: 0x18cc,
  },
];

export const restOfWorldAccomplishments = [
  {
    title: 'Benchwarmers Challenge',
    description:
      'Never substitute and win in Professional difficulty or above against a Rest of World club.',
    points: 2,
    offset: 0x1928,
  },
  {
    title: 'Distribution Challenge',
    description:
      'Score 3 goals with 3 different players in Semi-Pro difficulty or above against a Rest of World club.',
    points: 2,
    offset: 0x1984,
  },
  {
    title: 'Late Goal: Rest of World',
    description:
      'Score with a player subbed in after 75+ minutes in Professional difficulty or above.',
    points: 3,
    offset: 0x19e0,
  },
  {
    title: 'Ekstraklasa',
    description: 'Win the Ekstraklasa.',
    points: 3,
    offset: 0x1a3c,
  },
  {
    title: 'Polska Puchar',
    description: 'Win the Puchar Polski.',
    points: 2,
    offset: 0x1a98,
  },
  {
    title: 'K-League Classic',
    description: 'Win the K-League.',
    points: 3,
    offset: 0x1af4,
  },
  {
    title: 'A-League',
    description: 'Win the A-League.',
    points: 3,
    offset: 0x1b50,
  },
  {
    title: 'Airtricity League',
    description: 'Win the Airtricity League.',
    points: 3,
    offset: 0x1bac,
  },
  {
    title: 'International Club Championship',
    description: 'Win the International Club Championship.',
    points: 3,
    offset: 0x1c08,
  },
  {
    title: 'Russian League',
    description: 'Win the Russian League.',
    points: 3,
    offset: 0x1c64,
  },
  {
    title: 'Russian Cup',
    description: 'Win the Russian Cup.',
    points: 2,
    offset: 0x1cc0,
  },
];

export const masterAccomplishments = [
  {
    title: 'Offside Master',
    description:
      'Win without getting offsides in World Class difficulty or above.',
    points: 3,
    offset: 0x20b4,
  },
  {
    title: 'Goalscorer Keeper',
    description: 'Score with a goalie in Professional difficulty or above.',
    points: 3,
    offset: 0x2110,
  },
  {
    title: 'Quickdraw Master',
    description: 'Score within 15 minutes in World Class difficulty or above.',
    points: 3,
    offset: 0x216c,
  },
  {
    title: 'Distribution Master',
    description:
      'Score 5 goals with 5 different players in Professional difficulty or above.',
    points: 3,
    offset: 0x21c8,
  },
  {
    title: 'Fair Play Master',
    description:
      'Win a match without any bookings in World Class difficulty or above.',
    points: 3,
    offset: 0x2224,
  },
  {
    title: 'Hat Trick Master',
    description: 'Score a Hat Trick in World Class difficulty or above.',
    points: 5,
    offset: 0x2280,
  },
  {
    title: 'Clean Sheet Master',
    description:
      'Win a match with a clean sheet in World Class difficulty or above.',
    points: 4,
    offset: 0x22dc,
  },
  {
    title: 'Master Goalkeeper',
    description: 'Record 10 Clean Sheets in Be a Keeper.',
    points: 3,
    offset: 0x2394,
  },
];

export const scenarioAccomplishments = [
  {
    title: 'I',
    description:
      'Use Scenario settings to assign your club 0 subs available. Win the match against a club from the United Kingdom.',
    points: 2,
    offset: 0x00,
  },
  {
    title: 'II',
    description:
      'Use Scenario settings to assign your club 0 subs and 2 injuries. Win the match.',
    points: 2,
    offset: 0x564,
  },
  {
    title: 'III',
    description:
      'Use Scenario settings to start a 0-0 match in the 2nd half and win by 3 goals.',
    points: 2,
    offset: 0x9b4,
  },
  {
    title: 'IV',
    description:
      'Use Scenario settings to start a 0-0 match in the 85th minute. You must win.',
    points: 3,
    offset: 0xda8,
  },
  {
    title: 'V',
    description:
      'Use Scenario settings to start a match in the 1st half of extra time down 1-2 and win.',
    points: 3,
    offset: 0xe04,
  },
  {
    title: 'VI',
    description:
      'Use Scenario settings to assign your opponent a 1-0 lead. Win the match.',
    points: 2,
    offset: 0x119c,
  },
  {
    title: 'VII',
    description:
      'Use Scenario settings to start a match in the 2nd half of extra time, score tied and win.',
    points: 2,
    offset: 0x11f8,
  },
  {
    title: 'VIII',
    description:
      'Use Scenario settings to assign your club 1 red card. Win against a club from Scandinavia.',
    points: 2,
    offset: 0x1648,
  },
  {
    title: 'IX',
    description:
      'Use Scenario settings to assign your opponent a 3-0 lead. Win the match.',
    points: 2,
    offset: 0x16a4,
  },
  {
    title: 'X',
    description:
      'Use Scenario settings to assign your opponent a 5-0 lead in the 10th minute in Professional difficulty or above and win.',
    points: 4,
    offset: 0x2338,
  },
];

export const scenarioSettings = {
  ball: {
    kickoff: 0x00,
    throwInDef: 0x01,
    throwInAtt: 0x02,
    freeKickDef: 0x03,
    freeKickAtt: 0x04,
    cornerLeft: 0x05,
    cornerRight: 0x06,
    penaltyKick: 0x07,
    goalKick: 0x08,
  },
  half: {
    firstHalf: 0x00,
    secondHalf: 0x01,
    extraTimeFirstHalf: 0x02,
    extraTimeSecondHalf: 0x03,
  },
  extraTime: {
    classic: 0x00,
    silverGoal: 0x01,
    goldenGoal: 0x02,
    penaltyShootout: 0x03,
    none: 0x04,
  },
};

export const enduranceAccomplishments = [
  {
    title: 'Beginner Streaker',
    description: 'Achieve a 5 game winning streak in any difficulty level.',
    points: 2,
    offset: 0x1d1c,
  },
  {
    title: 'Intermediate Streaker',
    description: 'Achieve a 10 game winning streak in any difficulty level.',
    points: 5,
    offset: 0x1d78,
  },
  {
    title: 'Master Streaker',
    description: 'Achieve a 20 game winning streak in any difficulty level.',
    points: 10,
    offset: 0x1dd4,
  },
  {
    title: 'Beginner Scorer',
    description: 'Score a total of 10 goals in any difficulty level.',
    points: 2,
    offset: 0x1e30,
  },
  {
    title: 'Intermediate Scorer',
    description: 'Score a total of 50 goals in any difficulty level.',
    points: 5,
    offset: 0x1e8c,
  },
  {
    title: 'Master Scorer',
    description: 'Score a total of 100 goals in any difficulty level.',
    points: 10,
    offset: 0x1ee8,
  },
  {
    title: 'Beginner Winner',
    description: 'Win a total of 10 games in any difficulty level.',
    points: 2,
    offset: 0x1f44,
  },
  {
    title: 'Intermediate Winner',
    description: 'Win a total of 25 games in any difficulty level.',
    points: 5,
    offset: 0x1fa0,
  },
  {
    title: 'Experienced Winner',
    description: 'Win a total of 50 games in any difficulty level.',
    points: 10,
    offset: 0x1ffc,
  },
  {
    title: 'Master Winner',
    description: 'Win a total of 100 games in any difficulty level.',
    points: 25,
    offset: 0x2058,
  },
];
