export const richPresenceValues = {
  car: {
    0xffffffff: 'No car',
    0x0: 'Mazda RX-7 (FD3S)',
    0x1: 'Mazda RX-7 (FC3S)',
    0x2: 'Mazda RX-8',
    0x3: 'Mazda Mx-5 Miata',
    0x4: 'Mitsubishi Lancer Evolution VIII MR GSR',
    0x5: 'Mitsubishi Lancer GSR Evolution V',
    0x6: 'Mitsubishi GTO TWIN TURBO MR',
    0x7: 'Nissan Skyline GT-R V-Spec II Nur',
    0x8: 'Nissan Skyline GT-R V-Spec II',
    0x9: 'Nissan Gloria Gran Turismo 300 ULTIMA',
    0xa: 'Nissan Fairlady Z Version S',
    0xb: 'Nissan Fairlady Z 300ZX TWIN TURBO 2by2',
    0xc: 'Nissan Fairlady Z Z-L',
    0xd: 'Nissan Silvia Spec-R',
    0xe: "Nissan Silvia K's",
    0xf: 'Nissan 180SX Type X',
    0x10: 'Subaru Impreza WRX STi spec C',
    0x11: 'Subaru Impreza WRX typeRA STi version VI',
    0x12: 'Subaru Legacy B4 2.0GT spec.B',
    0x13: 'Toyota Supra RZ',
    0x14: 'Toyota Crown ATHLETE G Package',
    0x15: 'Toyota Altezza RS200 L EDITION',
    0x16: 'Toyota Sprinter Trueno GT-APEX 3-door',
    0x17: 'Toyota Celica SS-II Super Strut Package',
    0x18: 'Toyota MR-S S Edition',
    0x19: 'Jackknife',
    0x1a: 'Purple Meteor',
    0x1b: 'Exhaust Eve',
    0x1c: 'White Charisma',
    0x1d: 'Silver Wolf',
    0x1e: 'Midnight Cinderella',
    0x1f: 'Midnight Rose',
    0x20: 'Death Driver',
    0x21: 'Triple Claw',
    0x22: 'Hard Weapon',
    0x23: 'Melancholy Angel',
    0x24: 'Emperor',
    0x25: 'Grief Pluto',
    0x26: 'Unknown',
    0x27: 'Nightmare',
    0x28: 'Happy Chappy',
    0x29: 'Mr. Othello',
    0x2a: 'Spirit Crusher',
    0x2b: 'Rolling Guy No. 1',
    0x2c: 'Blue Speed',
    0x2d: 'Killing Machine',
    0x2e: 'Hearing Master',
    0x2f: 'Immovable Chief',
    0x30: 'Crimson Stardust',
    0x31: 'Blue Comet',
    0x32: 'Lemon Flavor',
    0x33: 'Silver Nobleman',
    0x34: 'Full Moon Fanatic',
    0x35: "Naniwa's Warship",
    0x36: 'Marvelous Invincible',
    0x37: 'Jackknife',
    0x38: 'Purple Meteor',
    0x39: 'Exhaust Eve',
    0x3a: 'White Charisma',
    0x3b: 'Silver Wolf',
    0x3c: 'Midnight Cinderella',
    0x3d: 'Midnight Rose',
    0x3e: 'Death Driver',
    0x3f: 'Triple Claw',
    0x40: 'Hard Weapon',
    0x41: 'Melancholy Angel',
    0x42: 'Emperor',
    0x43: 'Grief Pluto',
    0x44: 'Unknown',
    0x45: 'Nightmare',
  },
  area: {
    0x0: 'Kanda Bridge',
    0x1: 'Ginza',
    0x2: 'Fukuzumi',
    0x3: 'Ariake',
    0x4: 'Daiba',
    0x5: 'Ooi',
    0x6: 'Airport Ctrl',
    0x7: 'E. Ougi Isle',
    0x8: 'Daikoku Futo',
    0x9: 'Minato Mirai',
    0xa: 'Shioiri',
    0xb: 'Haneda',
    0xc: 'Shibaura',
    0xd: 'Shiba Park',
    0xe: 'Kasumigaseki',
  },
  team: {
    0x0: 'Departures',
    0x1: 'Galaxy Racers',
    0x2: 'Highway Outlaws',
    0x3: 'Unlimited',
    0x4: 'Another Star',
    0x5: 'Fine Drive',
    0x6: 'R.R.',
    0x7: 'Infinity',
    0x8: 'No Loser',
    0x9: 'Speed Masters',
    0xa: 'Free Way',
    0xb: 'Neo Limited',
    0xc: 'Shinen-Gumi',
    0xd: 'The Road of Justice',
    0xe: 'Rolling Guys',
    0xf: 'Wanderers',
  },
  track: {
    0x00: 'C1 Inside',
    0x01: 'C1 Outside',
    0x02: 'Ring Road R.',
    0x03: 'Ring Road L.',
    0x04: 'Down Coast',
    0x05: 'Up Coast',
    0x06: 'Y.R.Road Right',
    0x07: 'Y.R.Road Left',
    0x08: 'Yokohane Down',
    0x09: 'Yokohane Up',
  },
};

export const rivals = [
  // Departures
  {
    name: 'Happy Chappy',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa46190,
    beatAddress: 0xa461a8,
  },
  {
    name: 'Sweet Surrender',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa46200,
    beatAddress: 0xa46218,
  },
  {
    name: 'Cool Site',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa46270,
    beatAddress: 0xa46288,
  },
  {
    name: 'Mr. Finance',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa462e0,
    beatAddress: 0xa462f8,
  },
  {
    name: 'Upbeat',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa46350,
    beatAddress: 0xa46368,
  },
  {
    name: 'Pimp Daddy',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa463c0,
    beatAddress: 0xa463d8,
  },
  {
    name: 'The Sad Barbarian',
    team: 'Departures',
    points: 5,
    teamAddress: 0xa46430,
    beatAddress: 0xa46448,
  },
  // Galaxy Racers
  {
    name: 'Mister Othello',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa464a0,
    beatAddress: 0xa464b8,
  },
  {
    name: 'Broken Arrow',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa46510,
    beatAddress: 0xa46528,
  },
  {
    name: 'Sir Exotica',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa46580,
    beatAddress: 0xa46598,
  },
  {
    name: 'King of C1',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa465f0,
    beatAddress: 0xa46608,
  },
  {
    name: 'Seriously Saturday',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa46660,
    beatAddress: 0xa46678,
  },
  {
    name: 'C1 Sabrina',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa466d0,
    beatAddress: 0xa466e8,
  },
  {
    name: 'Always in the Red',
    team: 'Galaxy Racers',
    points: 5,
    teamAddress: 0xa46740,
    beatAddress: 0xa46758,
  },
  // Highway Outlaws
  {
    name: 'Spirit Crusher',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa467b0,
    beatAddress: 0xa467c8,
  },
  {
    name: 'Pride Killer',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa46820,
    beatAddress: 0xa46838,
  },
  {
    name: 'Cruel Prince',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa46890,
    beatAddress: 0xa468a8,
  },
  {
    name: 'Mad Driver',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa46900,
    beatAddress: 0xa46918,
  },
  {
    name: 'Gentleman Driver',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa46970,
    beatAddress: 0xa46988,
  },
  {
    name: 'Totem Pole',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa469e0,
    beatAddress: 0xa469f8,
  },
  {
    name: 'Spiral',
    team: 'Highway Outlaws',
    points: 5,
    teamAddress: 0xa46a50,
    beatAddress: 0xa46a68,
  },
  // Unlimited
  {
    name: 'Killing Machine',
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46ac0,
    beatAddress: 0xa46ad8,
  },
  {
    name: 'Sleeping K',
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46b30,
    beatAddress: 0xa46b48,
  },
  {
    name: 'Burning Heart',
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46ba0,
    beatAddress: 0xa46bb8,
  },
  {
    name: 'Fantasia Boy',
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46c10,
    beatAddress: 0xa46c28,
  },
  {
    name: 'Bronze Ghost',
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46c80,
    beatAddress: 0xa46c98,
  },
  {
    name: "It's Showtime",
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46cf0,
    beatAddress: 0xa46d08,
  },
  {
    name: 'Solo Moment',
    team: 'Unlimited',
    points: 5,
    teamAddress: 0xa46d60,
    beatAddress: 0xa46d78,
  },
  // Another Star
  {
    name: 'Blue Speed',
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa46dd0,
    beatAddress: 0xa46de8,
  },
  {
    name: 'Fancy Footwork',
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa46e40,
    beatAddress: 0xa46e58,
  },
  {
    name: 'Quicksilver',
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa46eb0,
    beatAddress: 0xa46ec8,
  },
  {
    name: 'Miura the Razor',
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa46f20,
    beatAddress: 0xa46f38,
  },
  {
    name: 'Red Roar',
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa46f90,
    beatAddress: 0xa46fa8,
  },
  {
    name: "Drivin' DJ",
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa47000,
    beatAddress: 0xa47018,
  },
  {
    name: 'Exotic Butterfly',
    team: 'Another Star',
    points: 5,
    teamAddress: 0xa47070,
    beatAddress: 0xa47088,
  },
  // Fine Drive
  {
    name: 'Shooting Star',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa470e0,
    beatAddress: 0xa470f8,
  },
  {
    name: 'Sylvester',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa47150,
    beatAddress: 0xa47168,
  },
  {
    name: 'Drifter from Hades',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa471c0,
    beatAddress: 0xa471d8,
  },
  {
    name: 'Sonic Runner',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa47230,
    beatAddress: 0xa47248,
  },
  {
    name: 'Drift Baby',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa472a0,
    beatAddress: 0xa472b8,
  },
  {
    name: 'Funky Monkey',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa47310,
    beatAddress: 0xa47328,
  },
  {
    name: 'Natural-Born Soldier',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa47380,
    beatAddress: 0xa47398,
  },
  {
    name: 'Free Bird',
    team: 'Fine Drive',
    points: 5,
    teamAddress: 0xa473f0,
    beatAddress: 0xa47408,
  },
  // R.R.
  {
    name: 'Platinum Prince',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa47460,
    beatAddress: 0xa47478,
  },
  {
    name: 'Cornering Artist',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa474d0,
    beatAddress: 0xa474e8,
  },
  {
    name: 'Grand-Slam Manager',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa47540,
    beatAddress: 0xa47558,
  },
  {
    name: 'Hiroshi',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa475b0,
    beatAddress: 0xa475c8,
  },
  {
    name: 'Amnesia',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa47620,
    beatAddress: 0xa47638,
  },
  {
    name: 'Risky Kitty',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa47690,
    beatAddress: 0xa476a8,
  },
  {
    name: 'Dark Phoenix',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa47700,
    beatAddress: 0xa47718,
  },
  {
    name: 'Superfast Superstar',
    team: 'R.R.',
    points: 5,
    teamAddress: 0xa47770,
    beatAddress: 0xa47788,
  },
  // Infinity
  {
    name: 'Mr. Invincible',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa477e0,
    beatAddress: 0xa477f8,
  },
  {
    name: 'Host with the Most',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa47850,
    beatAddress: 0xa47868,
  },
  {
    name: '20/20 Vision',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa478c0,
    beatAddress: 0xa478d8,
  },
  {
    name: 'Love Hunter',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa47930,
    beatAddress: 0xa47948,
  },
  {
    name: 'Northern Star',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa479a0,
    beatAddress: 0xa479b8,
  },
  {
    name: 'Red Moonlight',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa47a10,
    beatAddress: 0xa47a28,
  },
  {
    name: 'Smiling Assasin',
    team: 'Infinity',
    points: 5,
    teamAddress: 0xa47a80,
    beatAddress: 0xa47a98,
  },
  // No Loser
  {
    name: 'Awesome Osaka',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47af0,
    beatAddress: 0xa47b08,
  },
  {
    name: 'Nuclear Warhead',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47b60,
    beatAddress: 0xa47b78,
  },
  {
    name: 'Drive Me Crazy',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47bd0,
    beatAddress: 0xa47be8,
  },
  {
    name: 'Time Bomb',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47c40,
    beatAddress: 0xa47c58,
  },
  {
    name: 'Silent Searcher',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47cb0,
    beatAddress: 0xa47cc8,
  },
  {
    name: 'Commander Quick',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47d20,
    beatAddress: 0xa47d38,
  },
  {
    name: 'Hand Grenade',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47d90,
    beatAddress: 0xa47da8,
  },
  {
    name: 'Road Master',
    team: 'No Loser',
    points: 5,
    teamAddress: 0xa47e00,
    beatAddress: 0xa47e18,
  },
  // Speed Masters
  {
    name: 'Moon Howler',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa47e70,
    beatAddress: 0xa47e88,
  },
  {
    name: 'Fast Beat',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa47ee0,
    beatAddress: 0xa47ef8,
  },
  {
    name: 'Black Angel',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa47f50,
    beatAddress: 0xa47f68,
  },
  {
    name: 'Pearly Whites',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa47fc0,
    beatAddress: 0xa47fd8,
  },
  {
    name: 'Midnight Hawk',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa48030,
    beatAddress: 0xa48048,
  },
  {
    name: 'Big Disgrace',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa480a0,
    beatAddress: 0xa480b8,
  },
  {
    name: 'Lady White',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa48110,
    beatAddress: 0xa48128,
  },
  {
    name: 'Jackpot',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa48180,
    beatAddress: 0xa48198,
  },
  {
    name: 'Angry Princess',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa481f0,
    beatAddress: 0xa48208,
  },
  {
    name: 'Love Machine',
    team: 'Speed Masters',
    points: 5,
    teamAddress: 0xa48260,
    beatAddress: 0xa48278,
  },
  // Free Way
  {
    name: 'Blue Comet',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa482d0,
    beatAddress: 0xa482e8,
  },
  {
    name: 'Orange Head',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa48340,
    beatAddress: 0xa48358,
  },
  {
    name: 'Silver Fox',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa483b0,
    beatAddress: 0xa483c8,
  },
  {
    name: 'Old School',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa48420,
    beatAddress: 0xa48438,
  },
  {
    name: 'Ultimate Killer',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa48490,
    beatAddress: 0xa484a8,
  },
  {
    name: 'Night Knight',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa48500,
    beatAddress: 0xa48518,
  },
  {
    name: 'G-Force Junkie',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa48570,
    beatAddress: 0xa48588,
  },
  {
    name: 'Bombardier',
    team: 'Free Way',
    points: 5,
    teamAddress: 0xa485e0,
    beatAddress: 0xa485f8,
  },
  // Neo Limited
  {
    name: 'Lemon Flavor',
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa48650,
    beatAddress: 0xa48668,
  },
  {
    name: 'Lean and Mean',
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa486c0,
    beatAddress: 0xa486d8,
  },
  {
    name: 'High-Octane Poet',
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa48730,
    beatAddress: 0xa48748,
  },
  {
    name: "Keep on Truckin'",
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa487a0,
    beatAddress: 0xa487b8,
  },
  {
    name: 'Stormy Thursday',
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa48810,
    beatAddress: 0xa48828,
  },
  {
    name: 'Party Dress',
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa48880,
    beatAddress: 0xa48898,
  },
  {
    name: 'Ministry of Information',
    team: 'Neo Limited',
    points: 5,
    teamAddress: 0xa488f0,
    beatAddress: 0xa48908,
  },
  // Shinsen-Gumi
  {
    name: 'Steel Chief',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48960,
    beatAddress: 0xa48978,
  },
  {
    name: 'Iron Deputy Chief',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa489d0,
    beatAddress: 0xa489e8,
  },
  {
    name: 'Treacherous President',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48a40,
    beatAddress: 0xa48a58,
  },
  {
    name: 'Fearless 1st in Command',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48ab0,
    beatAddress: 0xa48ac8,
  },
  {
    name: 'Honest 2nd in Command',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48b20,
    beatAddress: 0xa48b38,
  },
  {
    name: 'Ominous 3rd in Command',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48b90,
    beatAddress: 0xa48ba8,
  },
  {
    name: 'Fierce 4th in Command',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48c00,
    beatAddress: 0xa48c18,
  },
  {
    name: 'Fiery 5th in Command',
    team: 'Shinsen-Gumi',
    points: 5,
    teamAddress: 0xa48c70,
    beatAddress: 0xa48c88,
  },
  // The Road of Justice
  {
    name: 'All Ears',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48ce0,
    beatAddress: 0xa48cf8,
  },
  {
    name: 'Highway Magician',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48d50,
    beatAddress: 0xa48d68,
  },
  {
    name: 'Fighting Nemoto',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48dc0,
    beatAddress: 0xa48dd8,
  },
  {
    name: 'Wall Man',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48e30,
    beatAddress: 0xa48e48,
  },
  {
    name: 'Flame Cannon',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48ea0,
    beatAddress: 0xa48eb8,
  },
  {
    name: 'Yellow Angel',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48f10,
    beatAddress: 0xa48f28,
  },
  {
    name: 'Happy Rabbit',
    team: 'The Road of Justice',
    points: 5,
    teamAddress: 0xa48f80,
    beatAddress: 0xa48f98,
  },
  // Rolling Guys
  {
    name: 'Rolling Man 1',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa48ff0,
    beatAddress: 0xa49008,
  },
  {
    name: 'Rolling Man 2',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa49060,
    beatAddress: 0xa49078,
  },
  {
    name: 'Rolling Man 3',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa490d0,
    beatAddress: 0xa490e8,
  },
  {
    name: 'Rolling Man 4',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa49140,
    beatAddress: 0xa49158,
  },
  {
    name: 'Rolling Man 5',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa491b0,
    beatAddress: 0xa491c8,
  },
  {
    name: 'Rolling Man 6',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa49220,
    beatAddress: 0xa49238,
  },
  {
    name: 'Rolling Man 7',
    team: 'Rolling Guys',
    points: 5,
    teamAddress: 0xa49290,
    beatAddress: 0xa492a8,
  },
  // Wanderers
  {
    name: 'Drift Dancer',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49300,
    beatAddress: 0xa49318,
  },
  {
    name: 'Haruo Garage',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49370,
    beatAddress: 0xa49388,
  },
  {
    name: 'Lone Wolf',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa493e0,
    beatAddress: 0xa493f8,
  },
  {
    name: 'Red-Hot Storm',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49450,
    beatAddress: 0xa49468,
  },
  {
    name: 'Original Evening Star',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa494c0,
    beatAddress: 0xa494d8,
  },
  {
    name: 'Jackknife',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49530,
    beatAddress: 0xa49548,
  },
  {
    name: 'Kamikaze Koji',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa495a0,
    beatAddress: 0xa495b8,
  },
  {
    name: 'Unkillable Clown',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49610,
    beatAddress: 0xa49628,
  },
  {
    name: 'Silent Barbarian',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49680,
    beatAddress: 0xa49698,
  },
  {
    name: 'Rolling Master',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa496f0,
    beatAddress: 0xa49708,
  },
  {
    name: 'Purple Meteor',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49760,
    beatAddress: 0xa49778,
  },
  {
    name: 'Master Position',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa497d0,
    beatAddress: 0xa497e8,
  },
  {
    name: 'Yellow Desperado',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49840,
    beatAddress: 0xa49858,
  },
  {
    name: 'Sweet Hips',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa498b0,
    beatAddress: 0xa498c8,
  },
  {
    name: 'Stormchaser',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49920,
    beatAddress: 0xa49938,
  },
  {
    name: 'Slicing Ghost',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49990,
    beatAddress: 0xa499a8,
  },
  {
    name: 'Exhaust Eve',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49a00,
    beatAddress: 0xa49a18,
  },
  {
    name: 'Bloody Mary',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49a70,
    beatAddress: 0xa49a88,
  },
  {
    name: 'Eternal Flower',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49ae0,
    beatAddress: 0xa49af8,
  },
  {
    name: 'Impatient Princess',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49b50,
    beatAddress: 0xa49b68,
  },
  {
    name: 'Golden Boy',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49bc0,
    beatAddress: 0xa49bd8,
  },
  {
    name: 'Io',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49c30,
    beatAddress: 0xa49c48,
  },
  {
    name: 'Late-Night Cinderella',
    team: 'Wanderers',
    points: 4,
    teamAddress: 0xa49ca0,
    beatAddress: 0xa49cb8,
  },
  {
    name: 'Glamorous Mami',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49d10,
    beatAddress: 0xa49d28,
  },
  {
    name: 'Pin Drop',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49d80,
    beatAddress: 0xa49d98,
  },
  {
    name: 'Raspberry Kiss',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49df0,
    beatAddress: 0xa49e08,
  },
  {
    name: 'Manabe the Craftman',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49e60,
    beatAddress: 0xa49e78,
  },
  {
    name: 'Night Wolf',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49ed0,
    beatAddress: 0xa49ee8,
  },
  {
    name: 'Super-Shifter Takuya',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa49f40,
    beatAddress: 0xa49f58,
  },
  {
    name: 'Tomorrow Again',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa49fb0,
    beatAddress: 0xa49fc8,
  },
  {
    name: 'Redlining Editor',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a020,
    beatAddress: 0xa4a038,
  },
  {
    name: 'Shimokitazawa 2000 cc',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a090,
    beatAddress: 0xa4a0a8,
  },
  {
    name: 'Perfect Score',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a100,
    beatAddress: 0xa4a118,
  },
  {
    name: 'Red Demon',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a170,
    beatAddress: 0xa4a188,
  },
  {
    name: 'Full Course',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a1e0,
    beatAddress: 0xa4a1f8,
  },
  {
    name: 'Illusion B',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a250,
    beatAddress: 0xa4a268,
  },
  {
    name: 'Ignorant Wisdom',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a2c0,
    beatAddress: 0xa4a2d8,
  },
  {
    name: 'Wild Heart',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a330,
    beatAddress: 0xa4a348,
  },
  {
    name: 'Speed Box',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a3a0,
    beatAddress: 0xa4a3b8,
  },
  {
    name: 'Masked Entracer',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a410,
    beatAddress: 0xa4a428,
  },
  {
    name: 'Jintei',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a480,
    beatAddress: 0xa4a498,
  },
  {
    name: 'Eulogy to Limits',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a4f0,
    beatAddress: 0xa4a508,
  },
  {
    name: 'Jet Skater',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a560,
    beatAddress: 0xa4a578,
  },
  {
    name: 'Mad Fatso',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a5d0,
    beatAddress: 0xa4a5e8,
  },
  {
    name: 'Ono the Technician',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a640,
    beatAddress: 0xa4a658,
  },
  {
    name: 'Black Dragon',
    team: 'Wanderers',
    points: 3,
    teamAddress: 0xa4a6b0,
    beatAddress: 0xa4a6c8,
  },
  {
    name: 'Dream Cloud',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a720,
    beatAddress: 0xa4a738,
  },
  {
    name: 'Samurai Gambler',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a790,
    beatAddress: 0xa4a7a8,
  },
  {
    name: 'Wild Child',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4a800,
    beatAddress: 0xa4a818,
  },
  {
    name: 'Off-Balanced Ishii',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a870,
    beatAddress: 0xa4a888,
  },
  {
    name: 'Tree Hugger',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4a8e0,
    beatAddress: 0xa4a8f8,
  },
  {
    name: 'Ultimate Jaguar',
    team: 'Wanderers',
    points: 3,
    teamAddress: 0xa4a950,
    beatAddress: 0xa4a968,
  },
  {
    name: "Wolves' Requiem",
    team: 'Wanderers',
    points: 3,
    teamAddress: 0xa4a9c0,
    beatAddress: 0xa4a9d8,
  },
  {
    name: 'Mosquito Lemon',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4aa30,
    beatAddress: 0xa4aa48,
  },
  {
    name: 'Iron Racer',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4aaa0,
    beatAddress: 0xa4aab8,
  },
  {
    name: 'King of Paradise',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4ab10,
    beatAddress: 0xa4ab28,
  },
  {
    name: 'Sherpa Nekozawa',
    team: 'Wanderers',
    points: 3,
    teamAddress: 0xa4ab80,
    beatAddress: 0xa4ab98,
  },
  {
    name: 'Hard Weapon',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4abf0,
    beatAddress: 0xa4ac08,
  },
  {
    name: 'Loyal Knight',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4ac60,
    beatAddress: 0xa4ac78,
  },
  {
    name: 'Gentle Rain',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4acd0,
    beatAddress: 0xa4ace8,
  },
  {
    name: 'Final Flight',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4ad40,
    beatAddress: 0xa4ad58,
  },
  {
    name: 'Tarmac Suzuki',
    team: 'Wanderers',
    points: 3,
    teamAddress: 0xa4adb0,
    beatAddress: 0xa4adc8,
  },
  {
    name: 'Lamenting Pluto',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4ae20,
    beatAddress: 0xa4ae38,
  },
  {
    name: 'Cry Baby',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4ae90,
    beatAddress: 0xa4aea8,
  },
  {
    name: 'Stalking Hammer',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4af00,
    beatAddress: 0xa4af18,
  },
  {
    name: 'Stealthy Groupie',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4af70,
    beatAddress: 0xa4af88,
  },
  {
    name: 'Texas Wolf',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4afe0,
    beatAddress: 0xa4aff8,
  },
  {
    name: 'Hip-Hop Red',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b050,
    beatAddress: 0xa4b068,
  },
  {
    name: 'Sad Angel',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4b0c0,
    beatAddress: 0xa4b0d8,
  },
  {
    name: 'Shonan Man',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b130,
    beatAddress: 0xa4b148,
  },
  {
    name: 'Swifty Valkyrie',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4b1a0,
    beatAddress: 0xa4b1b8,
  },
  {
    name: 'Highway Ninja',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b210,
    beatAddress: 0xa4b228,
  },
  {
    name: 'Yokohane Jet Fighter',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b280,
    beatAddress: 0xa4b298,
  },
  {
    name: 'Death Driver',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4b2f0,
    beatAddress: 0xa4b308,
  },
  {
    name: 'Speed Freak',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b360,
    beatAddress: 0xa4b378,
  },
  {
    name: 'Starting Dash',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b3d0,
    beatAddress: 0xa4b3e8,
  },
  {
    name: 'Gold License',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b440,
    beatAddress: 0xa4b458,
  },
  {
    name: 'King of Entertainment',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b4b0,
    beatAddress: 0xa4b4c8,
  },
  {
    name: 'Bloody Rose',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b520,
    beatAddress: 0xa4b538,
  },
  {
    name: 'Midnight Rose',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4b590,
    beatAddress: 0xa4b5a8,
  },
  {
    name: 'Caffeine Times Three',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b600,
    beatAddress: 0xa4b618,
  },
  {
    name: 'Infernal Machine',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b670,
    beatAddress: 0xa4b688,
  },
  {
    name: 'Prodigal Son',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b6e0,
    beatAddress: 0xa4b6f8,
  },
  {
    name: 'Alexander the Great',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b750,
    beatAddress: 0xa4b768,
  },
  {
    name: 'Red-Hot Mirage',
    team: 'Wanderers',
    points: 2,
    teamAddress: 0xa4b7c0,
    beatAddress: 0xa4b7d8,
  },
  {
    name: 'Mr. Charisma',
    team: 'Wanderers',
    points: 5,
    teamAddress: 0xa4b830,
    beatAddress: 0xa4b848,
  },
  {
    name: 'Driver with No Name',
    team: 'Wanderers',
    points: 10,
    teamAddress: 0xa4b8a0,
    beatAddress: 0xa4b8b8,
  },
];

export const timeAttackTracks = [
  {
    name: 'C1 Inside',
    target: 0,
    id: 0x00,
  },
  {
    name: 'C1 Outside',
    target: 0,
    id: 0x01,
  },
  {
    name: 'Ring Road R.',
    target: 0,
    id: 0x02,
  },
  {
    name: 'Ring Road L.',
    target: 0,
    id: 0x03,
  },
  {
    name: 'Down Coast',
    target: 275,
    id: 0x04,
  },
  {
    name: 'Up Coast',
    target: 270,
    id: 0x05,
  },
  {
    name: 'Y.R.Road Right',
    target: 0,
    id: 0x06,
  },
  {
    name: 'Y.R.Road Left',
    target: 0,
    id: 0x07,
  },
  {
    name: 'Yokohane Down',
    target: 0,
    id: 0x08,
  },
  {
    name: 'Yokohane Up',
    target: 0,
    id: 0x09,
  },
];
